### ISSUE TITLE
uniform file structure for the repo?

### ISSUE THREAD

**Issue by andreyorst** [clj-kondo/config#9]
Some library hooks are stored in:

    lib-name/.clj-kondo/hooks/lib-name/hook-name.clj

Let's call it "variant A". And some are using:

    lib-name/.clj-kondo/hooks/hook-name.clj

, which I'll refer to as "variant B".

Having different paths for different libraries it makes a bit harder to reason about when copying configs around manually.

I'm not sure, but I think it would be better, if all libs used variant A, since it is more futureproof since it matches Clojure's namespacing style, and can easily be copied over to a certain `hooks` directory

**Comment by borkdude** [comment]
I think variant A is better. In fact, I was thinking of the convention:

lib-org.lib-name/hook-name.clj to prevent clashes.

Also see https://github.com/clj-kondo/config/issues/1

**Comment by borkdude** [comment]
I think a variant where we include the lib org + lib name is better (as a two-level directory), to prevent clashes. Also see #1.

**Comment by borkdude** [comment]
I now refactored it to org+lib-name without an extra hooks parent dir.

**Comment by borkdude** [comment]
Also see https://github.com/borkdude/clj-kondo/blob/master/doc/config.md#Exporting-and-importing-configuration
